services:
  db:
    image: postgres:15
    container_name: portal-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal-ne1
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrate:
    image: node:24-alpine
    container_name: portal-migrate
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Esperando Postgres...';
      until nc -z db 5432; do sleep 1; done;
      echo 'Postgres pronto!';
      npx drizzle-kit migrate;
      echo 'Migrations aplicadas!';
      "

  portal:
    build: .
    container_name: portal
    restart: unless-stopped
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - db
      - migrate
    command: pnpm start

volumes:
  postgres-data:
